/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class game_Controller */

#ifndef _Included_game_Controller
#define _Included_game_Controller
#ifdef __cplusplus
extern "C" {
#endif
#undef game_Controller_VIRGIN
#define game_Controller_VIRGIN 0L
#undef game_Controller_SCHEDULED
#define game_Controller_SCHEDULED 1L
#undef game_Controller_EXECUTED
#define game_Controller_EXECUTED 2L
#undef game_Controller_CANCELLED
#define game_Controller_CANCELLED 3L
#undef game_Controller_BUTTONS
#define game_Controller_BUTTONS 0L
#undef game_Controller_LSTICKX
#define game_Controller_LSTICKX 1L
#undef game_Controller_LSTICKY
#define game_Controller_LSTICKY 2L
#undef game_Controller_DPAD_UP
#define game_Controller_DPAD_UP 1L
#undef game_Controller_DPAD_DOWN
#define game_Controller_DPAD_DOWN 2L
#undef game_Controller_DPAD_LEFT
#define game_Controller_DPAD_LEFT 4L
#undef game_Controller_DPAD_RIGHT
#define game_Controller_DPAD_RIGHT 8L
#undef game_Controller_DEADZONE
#define game_Controller_DEADZONE 7000L
/*
 * Class:     game_Controller
 * Method:    getControllerState
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_game_Controller_getControllerState
  (JNIEnv *, jobject);

/*
 * Class:     game_Controller
 * Method:    loadXinput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_game_Controller_loadXinput
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
