/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TurtleGame_Controller */

#ifndef _Included_TurtleGame_Controller
#define _Included_TurtleGame_Controller
#ifdef __cplusplus
extern "C" {
#endif
#undef TurtleGame_Controller_BUTTONS
#define TurtleGame_Controller_BUTTONS 0L
#undef TurtleGame_Controller_LSTICKX
#define TurtleGame_Controller_LSTICKX 1L
#undef TurtleGame_Controller_LSTICKY
#define TurtleGame_Controller_LSTICKY 2L
#undef TurtleGame_Controller_DPAD_UP
#define TurtleGame_Controller_DPAD_UP 1L
#undef TurtleGame_Controller_DPAD_DOWN
#define TurtleGame_Controller_DPAD_DOWN 2L
#undef TurtleGame_Controller_DPAD_LEFT
#define TurtleGame_Controller_DPAD_LEFT 4L
#undef TurtleGame_Controller_DPAD_RIGHT
#define TurtleGame_Controller_DPAD_RIGHT 8L
#undef TurtleGame_Controller_DEADZONE
#define TurtleGame_Controller_DEADZONE 7000L
/*
 * Class:     TurtleGame_Controller
 * Method:    getControllerState
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_TurtleGame_Controller_getControllerState
  (JNIEnv *, jobject);

/*
 * Class:     TurtleGame_Controller
 * Method:    loadXinput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TurtleGame_Controller_loadXinput
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
